class AllCookiesList {
  final List<String> cookiesList = [
    'Aggie Blue Mint™',
    'Almond Coconut Fudge',
    'Almond Joy®',
    'Almond Sand Dollar',
    'Almost Everything Bagel',
    'Andes® Mint',
    'Apple Pie',
    'Banana Bread',
    'Banana Cream Pie',
    'Berries & Cream',
    'Berry Crunch',
    'Birthday Cake',
    'Birthday Cake Holiday',
    'Birthday Cake Patriotic',
    'Birthday Cake Valentine',
    'Birthday Cake ft. Oreo',
    'Biscoff™ Lava',
    'Biscoff™ White Chip',
    'Blue Monster Featuring CHIPS AHOY!®',
    'Blue Raspberry ft. ICEE®',
    'Blueberry Cheesecake',
    'Blueberry Crumb Cake',
    'Blueberry Muffin',
    'Boston Cream Pie',
    'Brownie Batter',
    'Brownie Sundae',
    'Bubble Gum',
    'Buckeye Brownie',
    'Butterfinger®',
    'Buttermilk Pancake',
    'Cake Batter',
    'Cake Batter Blondie',
    'Caramel Apple',
    'Caramel Cake',
    'Caramel Coconut Fudge',
    'Caramel Popcorn',
    'Caramel Pumpkin',
    'Caramel Shortbread ft. TWIX®',
    'Carrot Cake',
    'Cereal Milk Sandwich ft. PEBBLES® Cereal',
    'Cereal Milk ft. Fruity PEBBLES®',
    'Chocolate Cake',
    'Chocolate Cake ft. HEATH®',
    'Chocolate Caramel',
    'Chocolate Cookies and Cream',
    'Chocolate Covered Strawberry',
    'Chocolate Crumb Cake Featuring OREO®',
    'Chocolate Crunch',
    'Chocolate Cupcake',
    'Chocolate Mallow Cupcake',
    'Chocolate Malt Featuring Tootsie Roll®',
    'Chocolate Orange Truffle',
    'Chocolate Peanut Butter Chip',
    'Chocolate Peanut Butter ft. Oreo®',
    'Chocolate Potato Chip',
    'Chocolate Pumpkin Cheesecake',
    'Chocolate Sprinkle',
    'Chocolate Strawberry Cheesecake',
    'Chocolate Toffee Cake',
    'Chocolate ft. Reese’s Puffs',
    'Chocolate ft. York Peppermint',
    'Churro',
    'Cinnamon Fry Bread',
    'Cinnamon Pretzel',
    'Cinnamon Swirl',
    'Cinnamon ft. Cinnamon Toast Crunch™',
    'Circus Animal',
    'Classic Krispy Bar',
    'Classic Oatmeal',
    'Classic Peanut Butter',
    'Classic Pink Sugar',
    'Coconut Cake',
    'Coconut Cream',
    'Coconut Lime',
    'Coconut White Chip',
    'Confetti (Valentine)',
    'Confetti Cake',
    'Cookie Butter Ice Cream',
    'Cookie Butter White Chip',
    'Cookie Cup',
    'Cookie Dough',
    'Cookies & Cream',
    'Cookies & Cream Milkshake',
    'Cornbread',
    'Cornbread Honey Cake',
    'Cornflake Marshmallow',
    'Cotton Candy',
    'Cowboy Cookie',
    'Cranberry Craze',
    'Cranberry White Chip ft. Ocean Spray®',
    'Dark Dream',
    'Dirt Cake',
    'Dirt Cake ft. Otto',
    'Double Fudge Brownie',
    'Double Trouble',
    'Dulce De Leche',
    'Eggnog',
    'French Silk Pie',
    'French Toast',
    'Fried Ice Cream',
    'Frozen Hot Chocolate',
    'Fruit Pizza',
    'Funfetti',
    'Funfetti Milkshake',
    'Galaxy Brownie',
    'German Chocolate Cake',
    'Gingerbread Cake',
    'Gingersnap',
    'Graham Cracker ft. Teddy Grahams®',
    'Green Mint ft. Andes®',
    'Hawaii Rainbow Cake',
    'Hazelnut Churro',
    'Hazelnut Mudslide',
    'Hazelnut Sea Salt',
    'Honey Bun',
    'Honey Graham Cracker',
    'Honeycomb',
    'Hot Chocolate',
    'Iced Oatmeal',
    'Kentucky Butter Cake',
    'Key Lime Pie',
    'Lemon Bar Cookie',
    'Lemon Blackberry',
    'Lemon Cheesecake',
    'Lemon Chiffon',
    'Lemon Crinkle',
    'Lemon Cupcake',
    'Lemon Glaze',
    'Lemon Poppy Seed',
    'Lemonade',
    'Limeade',
    'Lucky Charms',
    'Macadamia Nut',
    'Mallow Sandwich ft. OREO®',
    'Mango Frozen Yogurt',
    'Maple Bacon',
    'Maple Cinnamon Roll',
    'Maple Glaze',
    'Midnight Mint',
    'Milk Chocolate Chip',
    'Milk Glaze ft. Fruity PEBBLES™',
    'Minion Confetti',
    'Mint Brownie',
    'Mint Chip Ice Cream',
    'Molten Lava',
    'Mom’s Recipe',
    'Monster',
    'Mooncake',
    'Muddy Buddy',
    'Neapolitan',
    'New York Cheesecake',
    'Nilla Bean Cupcake',
    'Nutella Mudslide',
    'Nutella Sea Salt',
    'Oatmeal Chocolate Chip',
    'Oatmeal Chocolate Chip Muffin',
    'Oatmeal Raisin',
    'Oatmeal ft. ROLO®',
    'Old Fashioned Doughnut',
    'Orange Creamsicle',
    'Orange Roll',
    'Original featuring M&M’s® Candies',
    'Original featuring M&M’s® Candies (Valentines)',
    'Original featuring Peanut Butter M&M’S® Candies',
    'Original ft. Golden OREO® Cookie Pieces',
    'Original ft. KITKAT®',
    'Passion Fruit',
    'Peach Cobbler',
    'Peaches N’ Cream',
    'Peanut Butter & Jelly',
    'Peanut Butter Banana',
    'Peanut Butter Bar',
    'Peanut Butter Blossom',
    'Peanut Butter Brittle',
    'Peanut Butter Brownie',
    'Peanut Butter Chocolate Chip',
    'Peanut Butter Cookies & Cream',
    'Peanut Butter Creme featuring NUTTER BUTTER®',
    'Peanut Butter Crisp featuring Butterfinger®',
    'Peanut Butter Cup Featuring REESE’S',
    'Peanut Butter Jamwich',
    'Peanut Butter Nougat Featuring Snickers®',
    'Peanut Butter featuring Reese’s Pieces',
    'Peanut Butter ft. SNICKERS®',
    'Pecan Pie',
    'Peppermint Bark',
    'Pina Colada',
    'Pineapple Upside Down Cake',
    'Pineapple Whip',
    'Pink Doughnut',
    'Pink Velvet Cake',
    'Pumpkin Cake',
    'Pumpkin Chocolate Chip',
    'Pumpkin OREO® Cheesecake',
    'Pumpkin Pie',
    'Pumpkin Roll',
    'Raspberry Butter Cake',
    'Raspberry Cheesecake',
    'Raspberry Doughnut',
    'Raspberry Lemonade',
    'Red Velvet Cream Cheese',
    'Red Velvet White Chip',
    'Reese’s Chip',
    'Rocky Road',
    'Ruby Chocolate Chip',
    'Salted Caramel Cheesecake',
    'Samoa',
    'Sea Salt Butterscotch Pretzel',
    'Sea Salt Toffee',
    'Semi-Sweet Chocolate Chip',
    'Semi-Sweet Chocolate Chunk',
    'Sherbet',
    'Snickerdoodle',
    'Snickerdoodle Cupcake',
    'Sour Patch Kids',
    'Sticky Bun',
    'Strawberries N’ Cream',
    'Strawberry Cake',
    'Strawberry Cheesecake',
    'Strawberry Crumb Cake',
    'Strawberry Ice Cream Bar',
    'Strawberry Limeade Featuring NERDS®',
    'Strawberry Milk',
    'Strawberry Pop-tart',
    'Strawberry Shortcake',
    'Sugar (Shark)',
    'Sugar - Candy Eggs',
    'Sugar ft. Mother’s® Halloween Circus Animal™',
    'Sugar ft. Mother’s® Reindeer Games',
    'Sugar ft. Mother’s® Valentine X’s and O’s',
    'Sugar ft. TWIX®',
    'Sugar – Gold Coin',
    'Sugar – Pumpkin Candy',
    'S’mores',
    'S’mores Brownie',
    'Texas Sheet Cake',
    'Tres Leches',
    'Triple Berry Cobbler',
    'Triple Chocolate Chip',
    'Turtle',
    'Twix',
    'Ultimate Peanut Butter',
    'Vanilla Glaze ft. Cinnamon Toast Crunch™',
    'Vanilla Sugar',
    'Waffle',
    'Walnut Brownie Fudge',
    'Walnut Chocolate Chip Cookie',
    'Watermelon',
    'White Chocolate Chip',
    'Yellow Sugar',
  ];
}
